"""Initial tables

Revision ID: 3bb9ed2393b0
Revises: 
Create Date: 2025-11-06 12:55:42.733642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bb9ed2393b0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist_short_name', sa.String(length=100), nullable=False),
    sa.Column('artist_long_name', sa.String(length=200), nullable=False),
    sa.Column('dob', sa.String(length=10), nullable=True),
    sa.Column('dob_place', sa.String(length=200), nullable=True),
    sa.Column('dod', sa.String(length=10), nullable=True),
    sa.Column('dod_place', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artists_id'), 'artists', ['id'], unique=False)
    op.create_table('museums',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('name_unique', sa.String(length=100), nullable=True),
    sa.Column('contact', sa.String(length=100), nullable=True),
    sa.Column('profile', sa.String(length=255), nullable=True),
    sa.Column('profile_path', sa.String(length=500), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('country_code', sa.Integer(), nullable=True),
    sa.Column('zipcode', sa.Integer(), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name_unique')
    )
    op.create_index(op.f('ix_museums_id'), 'museums', ['id'], unique=False)
    op.create_table('paintings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('unique_title', sa.String(length=100), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('genre', sa.String(length=100), nullable=True),
    sa.Column('materials', sa.JSON(), nullable=True),
    sa.Column('size', sa.String(length=100), nullable=True),
    sa.Column('profile', sa.String(length=255), nullable=True),
    sa.Column('profile_path', sa.String(length=500), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('period', sa.String(length=100), nullable=True),
    sa.Column('style', sa.JSON(), nullable=True),
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.Column('museum_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ),
    sa.ForeignKeyConstraint(['museum_id'], ['museums.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unique_title')
    )
    op.create_index(op.f('ix_paintings_id'), 'paintings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_paintings_id'), table_name='paintings')
    op.drop_table('paintings')
    op.drop_index(op.f('ix_museums_id'), table_name='museums')
    op.drop_table('museums')
    op.drop_index(op.f('ix_artists_id'), table_name='artists')
    op.drop_table('artists')
    # ### end Alembic commands ###
